name: (English) Problem report form
about: To report broken websites, lists, and/or functions
title: ''
labels: Problem report
assignees: ''
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)
      description: This includes the website it happened on (if applicable), and an example page from that site.
      placeholder: Write the problem here.
    validations:
      required: true
  - type: textarea
     id: what-happened
    attributes:
      label: Add screenshots below if needed
      placeholder: Paste screenshots here.
    validations:
      required: false
  - type: textarea
    id: log-photo
    attributes:
      label: Add a screenshot of the extension's logger
      description: If you're using uBlock Origin, it's recommended to filter the selection down to Blocked+Allowed, to reduce the amount of (mostly irrelevant) "white" log entries.
      placeholder: Write the problem here.
    validations:
      required: false
  - type: dropdown
    id: adblockers
    attributes:
      label: Which adblocker(s) did you use when testing this?
      multiple: true
      options:
        - uBlock Origin
        - AdGuard (Paid desktop version)
        - AdGuard (for browsers)
        - Adblock Plus
        - AdBlock
        - AdGuard Home
        - Blokada
        - I Don't Care About Cookies (The extension)
        - Firefox's built-in tracking protection
        - Vivaldi's built-in adblocker
        - AdNauseam
        - pfBlockerNG
        - Other
    validations:
      required: true
  - type: textarea
    id: adblockers-version
    attributes:
      label: Adblocker version(s)
      placeholder: Write the version number(s) and "Other" adblockers here.
    validations:
      required: false
  - type: textarea
    id: which-filterlists-did-you-use
    attributes:
      label: Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
      placeholder: Paste an image or textlist here.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser(s) did you use when testing this?
      multiple: true
      options:
        - Google Chrome
        - Firefox
        - Vivaldi
        - Brave Browser
        - Tor Browser
        - Chromium for Linux
        - Ungoogled Chromium
        - Midori Electron (not WebKit)
        - Opera (any variety)
        - Kiwi Browser
        - Other
    validations:
      required: true
  - type: textarea
    id: browsers-version
    attributes:
      label: Browser version(s)
      placeholder: Write the version number(s) and "Other" browsers here.
    validations:
      required: false
  - type: dropdown
    id: oses
    attributes:
      label: Which OS(s) did you use when testing this?
      multiple: true
      options:
        - Windows 10
        - macOS
        - Linux
        - Windows 8.1
        - Windows 7
        - Android
        - Other
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: OS version(s)
      placeholder: Write the version number(s) and "Other" OSs here.
    validations:
      required: false
