name: Update the ClearURLs uBo list
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '16 20,2 * * *'
  workflow_dispatch:
jobs:
  mklist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build list
      run: |
        pip3 install requests
        python scripts/compile.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update the list ClearURLs uBo list
          title: '[Bot] Update the list ClearURLs uBo list'
          body: >
            **Note: This is a bot. It's creator - iam-py-test - is not responsable for its actions**
            Updating ClearURLs for uBo list
          labels: bot
