name: RegEx text replacement
on: [push, pull_request, discussion_comment, issue_comment, fork]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "(&#40;/.*)([a-zA-Z])$2([a-zA-Z0-9|/-])"
          replace: "$1$2{2}$3"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
